use pcode_model::{Instruction, Opcode, Operand, Program, WORD};
use std::collections::HashSet;
use std::fmt::Write;

/// Errors during assembly emission.
#[derive(Debug)]
pub enum EmitError {
    /// A fmt::Write call failed.
    Fmt(std::fmt::Error),
    /// Global variable offset too large for single-instruction access.
    GlobalOffsetTooLarge { addr: u32 },
    /// Local variable offset too large for single-instruction access.
    LocalOffsetTooLarge { offset: u8 },
}

impl std::fmt::Display for EmitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EmitError::Fmt(e) => write!(f, "format error: {e}"),
            EmitError::GlobalOffsetTooLarge { addr } => {
                write!(f, "global offset too large: {addr} (max 42)")
            }
            EmitError::LocalOffsetTooLarge { offset } => {
                write!(f, "local offset too large: {offset} (max 41)")
            }
        }
    }
}

impl std::error::Error for EmitError {}

impl From<std::fmt::Error> for EmitError {
    fn from(e: std::fmt::Error) -> Self {
        EmitError::Fmt(e)
    }
}

/// Initial stack pointer address. Programs start with sp set here;
/// the stack grows downward from this address.
const STACK_TOP: u32 = 0x2000;

/// Emit COR24 assembly for a decoded p-code program.
///
/// Returns the complete assembly text as a string, ready to be written
/// to a `.s` file and assembled by the COR24 cross-assembler (as24).
pub fn emit_program(program: &Program, source_name: &str) -> Result<String, EmitError> {
    let mut e = Emitter::new(program);
    e.prologue(program, source_name)?;
    for instr in &program.instructions {
        e.instruction(instr)?;
    }
    e.epilogue(program)?;
    Ok(e.out)
}

// ── Emitter ────────────────────────────────────────────────────────

struct Emitter {
    out: String,
    /// P-code PCs that are jump/branch targets and need labels.
    targets: HashSet<u32>,
    /// Counter for generating unique skip labels (for conditional branches).
    skip_id: u32,
}

impl Emitter {
    fn new(program: &Program) -> Self {
        Self {
            out: String::with_capacity(8192),
            targets: collect_branch_targets(&program.instructions),
            skip_id: 0,
        }
    }

    fn next_skip(&mut self) -> u32 {
        let id = self.skip_id;
        self.skip_id += 1;
        id
    }

    // ── Prologue / epilogue ────────────────────────────────────────

    fn prologue(&mut self, program: &Program, source_name: &str) -> Result<(), EmitError> {
        writeln!(self.out, "; Generated by pc-aotc from {source_name}")?;
        writeln!(self.out, "; COR24 p-code AOT compiler output")?;
        writeln!(self.out)?;
        writeln!(self.out, "    la      sp, {STACK_TOP}")?;
        if program.entry_point != 0 {
            writeln!(self.out, "    la      r2, .L{:04X}", program.entry_point)?;
            writeln!(self.out, "    jmp     (r2)")?;
        }
        writeln!(self.out)?;
        Ok(())
    }

    fn epilogue(&mut self, program: &Program) -> Result<(), EmitError> {
        // Halt loop (target for halt opcode)
        writeln!(self.out, "_p24_halt:")?;
        writeln!(self.out, "    bra     _p24_halt")?;
        writeln!(self.out)?;

        // Global variable storage
        if program.global_count > 0 {
            let size = program.global_count as usize * WORD;
            writeln!(
                self.out,
                "; Global variables ({} words)",
                program.global_count
            )?;
            writeln!(self.out, "_p24_globals:")?;
            // Emit zero-initialized bytes
            for _ in 0..size {
                writeln!(self.out, "    .byte   0")?;
            }
            writeln!(self.out)?;
        }

        // Data segment (if any)
        if !program.data.is_empty() {
            writeln!(self.out, "; Data segment ({} bytes)", program.data.len())?;
            writeln!(self.out, "_p24_data:")?;
            for chunk in program.data.chunks(16) {
                let bytes: Vec<String> = chunk.iter().map(|b| format!("{b}")).collect();
                writeln!(self.out, "    .byte   {}", bytes.join(","))?;
            }
            writeln!(self.out)?;
        }

        Ok(())
    }

    // ── Instruction dispatch ───────────────────────────────────────

    fn instruction(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        // Emit label if this PC is a branch target or procedure entry
        if self.targets.contains(&instr.pc) {
            writeln!(self.out, ".L{:04X}:", instr.pc)?;
        }

        // Comment with p-code disassembly
        self.pcode_comment(instr)?;

        match instr.op {
            // Stack operations
            Opcode::Halt => self.op_halt()?,
            Opcode::Push => self.op_push(instr)?,
            Opcode::PushS => self.op_push_s(instr)?,
            Opcode::Dup => self.op_dup()?,
            Opcode::Drop => self.op_drop()?,
            Opcode::Swap => self.op_swap()?,
            Opcode::Over => self.op_over()?,

            // Arithmetic
            Opcode::Add => self.op_commutative_binop("add")?,
            Opcode::Sub => self.op_sub()?,
            Opcode::Mul => self.op_commutative_binop("mul")?,
            Opcode::Neg => self.op_neg()?,

            // Comparisons
            Opcode::Eq => self.op_eq()?,
            Opcode::Ne => self.op_ne()?,
            Opcode::Lt => self.op_lt()?,
            Opcode::Le => self.op_le()?,
            Opcode::Gt => self.op_gt()?,
            Opcode::Ge => self.op_ge()?,

            // Control flow
            Opcode::Jmp => self.op_jmp(instr)?,
            Opcode::Jz => self.op_jz(instr)?,
            Opcode::Jnz => self.op_jnz(instr)?,

            // Frame / variable access
            Opcode::Enter => self.op_enter(instr)?,
            Opcode::Leave => self.op_leave()?,
            Opcode::Loadl => self.op_loadl(instr)?,
            Opcode::Storel => self.op_storel(instr)?,
            Opcode::Loadg => self.op_loadg(instr)?,
            Opcode::Storeg => self.op_storeg(instr)?,

            // Unsupported — emit a comment so the file is still parseable
            _ => {
                writeln!(self.out, "    ; TODO: unsupported opcode {}", instr.op)?;
            }
        }
        writeln!(self.out)?;
        Ok(())
    }

    // ── Stack operations ───────────────────────────────────────────

    fn op_halt(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    la      r2, _p24_halt")?;
        writeln!(self.out, "    jmp     (r2)")?;
        Ok(())
    }

    fn op_push(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm24(val) = instr.operand {
            let sval = sign_extend_24(val);
            self.load_immediate("r0", sval)?;
            writeln!(self.out, "    push    r0")?;
        }
        Ok(())
    }

    fn op_push_s(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm8(val) = instr.operand {
            let sval = val as i8 as i32;
            self.load_immediate("r0", sval)?;
            writeln!(self.out, "    push    r0")?;
        }
        Ok(())
    }

    fn op_dup(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    lw      r0, 0(sp)")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    fn op_drop(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?;
        Ok(())
    }

    fn op_swap(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?;
        writeln!(self.out, "    pop     r1")?;
        writeln!(self.out, "    push    r0")?;
        writeln!(self.out, "    push    r1")?;
        Ok(())
    }

    fn op_over(&mut self) -> Result<(), EmitError> {
        // NOS is one word below TOS: sp+3
        writeln!(self.out, "    lw      r0, 3(sp)")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    // ── Arithmetic ─────────────────────────────────────────────────

    /// Emit a commutative binary op (add, mul): pop two, compute, push result.
    fn op_commutative_binop(&mut self, mnemonic: &str) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?; // TOS
        writeln!(self.out, "    pop     r1")?; // NOS
        writeln!(self.out, "    {mnemonic:<8}r0, r1")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    /// Sub: NOS - TOS. Non-commutative, so operand order matters.
    fn op_sub(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?; // TOS
        writeln!(self.out, "    pop     r1")?; // NOS
        writeln!(self.out, "    sub     r1, r0")?; // r1 = NOS - TOS
        writeln!(self.out, "    push    r1")?;
        Ok(())
    }

    /// Neg: -TOS. COR24 has no neg instruction, so compute 0 - TOS.
    fn op_neg(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r1")?; // TOS
        writeln!(self.out, "    mov     r0, z")?; // r0 = 0
        writeln!(self.out, "    sub     r0, r1")?; // r0 = 0 - TOS
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    // ── Comparisons ────────────────────────────────────────────────
    //
    // COR24 has: ceq (==), cls (signed <), clu (unsigned <).
    // The condition flag C is read via `mov rX, c`.
    // For ne/le/ge we compute the inverse by checking if C == 0.

    /// Eq: NOS == TOS → 1, else 0.
    fn op_eq(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?; // TOS
        writeln!(self.out, "    pop     r1")?; // NOS
        writeln!(self.out, "    ceq     r1, r0")?;
        writeln!(self.out, "    mov     r0, c")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    /// Ne: NOS != TOS → 1, else 0. Invert eq result.
    fn op_ne(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?;
        writeln!(self.out, "    pop     r1")?;
        writeln!(self.out, "    ceq     r1, r0")?; // C = (NOS == TOS)
        writeln!(self.out, "    mov     r0, c")?; // r0 = eq result
        writeln!(self.out, "    ceq     r0, z")?; // C = (r0 == 0) = not-equal
        writeln!(self.out, "    mov     r0, c")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    /// Lt: NOS < TOS (signed) → 1, else 0.
    fn op_lt(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?; // TOS
        writeln!(self.out, "    pop     r1")?; // NOS
        writeln!(self.out, "    cls     r1, r0")?; // C = (NOS < TOS)
        writeln!(self.out, "    mov     r0, c")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    /// Le: NOS <= TOS ⟺ ¬(TOS < NOS).
    fn op_le(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?; // TOS
        writeln!(self.out, "    pop     r1")?; // NOS
        writeln!(self.out, "    cls     r0, r1")?; // C = (TOS < NOS)
        writeln!(self.out, "    mov     r0, c")?; // r0 = (TOS < NOS)
        writeln!(self.out, "    ceq     r0, z")?; // C = ¬(TOS < NOS) = (NOS <= TOS)
        writeln!(self.out, "    mov     r0, c")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    /// Gt: NOS > TOS ⟺ TOS < NOS.
    fn op_gt(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?; // TOS
        writeln!(self.out, "    pop     r1")?; // NOS
        writeln!(self.out, "    cls     r0, r1")?; // C = (TOS < NOS) = (NOS > TOS)
        writeln!(self.out, "    mov     r0, c")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    /// Ge: NOS >= TOS ⟺ ¬(NOS < TOS).
    fn op_ge(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?; // TOS
        writeln!(self.out, "    pop     r1")?; // NOS
        writeln!(self.out, "    cls     r1, r0")?; // C = (NOS < TOS)
        writeln!(self.out, "    mov     r0, c")?; // r0 = (NOS < TOS)
        writeln!(self.out, "    ceq     r0, z")?; // C = ¬(NOS < TOS) = (NOS >= TOS)
        writeln!(self.out, "    mov     r0, c")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    // ── Control flow ───────────────────────────────────────────────

    /// Unconditional jump. Uses absolute addressing via la + jmp.
    fn op_jmp(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm24(addr) = instr.operand {
            writeln!(self.out, "    la      r2, .L{addr:04X}")?;
            writeln!(self.out, "    jmp     (r2)")?;
        }
        Ok(())
    }

    /// Jump if zero: pop TOS, branch to target if TOS == 0.
    fn op_jz(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm24(addr) = instr.operand {
            let skip = self.next_skip();
            writeln!(self.out, "    pop     r0")?;
            writeln!(self.out, "    ceq     r0, z")?; // C = (TOS == 0)
            writeln!(self.out, "    brf     .Lskip{skip}")?; // skip if not zero
            writeln!(self.out, "    la      r2, .L{addr:04X}")?;
            writeln!(self.out, "    jmp     (r2)")?;
            writeln!(self.out, ".Lskip{skip}:")?;
        }
        Ok(())
    }

    /// Jump if non-zero: pop TOS, branch to target if TOS != 0.
    fn op_jnz(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm24(addr) = instr.operand {
            let skip = self.next_skip();
            writeln!(self.out, "    pop     r0")?;
            writeln!(self.out, "    ceq     r0, z")?; // C = (TOS == 0)
            writeln!(self.out, "    brt     .Lskip{skip}")?; // skip if zero
            writeln!(self.out, "    la      r2, .L{addr:04X}")?;
            writeln!(self.out, "    jmp     (r2)")?;
            writeln!(self.out, ".Lskip{skip}:")?;
        }
        Ok(())
    }

    // ── Frame / variable access ────────────────────────────────────

    /// Enter: set up activation frame, allocate local variable slots.
    ///
    /// Frame layout (stack grows downward):
    /// ```text
    ///     [saved fp]    ← fp points here after "mov fp, sp"
    ///     [local 0]     ← fp - 3
    ///     [local 1]     ← fp - 6
    ///     ...
    ///     [local N-1]   ← fp - N*3
    ///     [eval stack]  ← sp (current top)
    /// ```
    fn op_enter(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm8(nlocals) = instr.operand {
            writeln!(self.out, "    push    fp")?;
            writeln!(self.out, "    mov     fp, sp")?;
            if nlocals > 0 {
                let size = nlocals as u32 * WORD as u32;
                writeln!(self.out, "    sub     sp, {size}")?;
            }
        }
        Ok(())
    }

    /// Leave: tear down activation frame (inverse of enter).
    fn op_leave(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    mov     sp, fp")?;
        writeln!(self.out, "    pop     fp")?;
        Ok(())
    }

    /// Load local variable at slot offset onto eval stack.
    fn op_loadl(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm8(slot) = instr.operand {
            let offset = local_frame_offset(slot)?;
            writeln!(self.out, "    lw      r0, {offset}(fp)")?;
            writeln!(self.out, "    push    r0")?;
        }
        Ok(())
    }

    /// Store TOS into local variable at slot offset.
    fn op_storel(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm8(slot) = instr.operand {
            let offset = local_frame_offset(slot)?;
            writeln!(self.out, "    pop     r0")?;
            writeln!(self.out, "    sw      r0, {offset}(fp)")?;
        }
        Ok(())
    }

    /// Load global variable onto eval stack.
    fn op_loadg(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm24(addr) = instr.operand {
            let byte_offset = addr as usize * WORD;
            writeln!(self.out, "    la      r1, _p24_globals")?;
            if byte_offset <= 127 {
                writeln!(self.out, "    lw      r0, {byte_offset}(r1)")?;
            } else {
                writeln!(self.out, "    la      r2, {byte_offset}")?;
                writeln!(self.out, "    add     r1, r2")?;
                writeln!(self.out, "    lw      r0, 0(r1)")?;
            }
            writeln!(self.out, "    push    r0")?;
        }
        Ok(())
    }

    /// Store TOS into global variable.
    fn op_storeg(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm24(addr) = instr.operand {
            let byte_offset = addr as usize * WORD;
            writeln!(self.out, "    pop     r0")?;
            writeln!(self.out, "    la      r1, _p24_globals")?;
            if byte_offset <= 127 {
                writeln!(self.out, "    sw      r0, {byte_offset}(r1)")?;
            } else {
                writeln!(self.out, "    la      r2, {byte_offset}")?;
                writeln!(self.out, "    add     r1, r2")?;
                writeln!(self.out, "    sw      r0, 0(r1)")?;
            }
        }
        Ok(())
    }

    // ── Helpers ────────────────────────────────────────────────────

    /// Emit a p-code disassembly comment line.
    fn pcode_comment(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        writeln!(self.out, "    ; {instr}")?;
        Ok(())
    }

    /// Emit instructions to load an immediate value into a register.
    /// Chooses the smallest encoding: lc (8-bit signed), lcu (8-bit unsigned), or la (24-bit).
    fn load_immediate(&mut self, reg: &str, val: i32) -> Result<(), EmitError> {
        if (-128..=127).contains(&val) {
            writeln!(self.out, "    lc      {reg}, {val}")?;
        } else if (0..=255).contains(&val) {
            writeln!(self.out, "    lcu     {reg}, {val}")?;
        } else {
            writeln!(self.out, "    la      {reg}, {val}")?;
        }
        Ok(())
    }
}

// ── Utility functions ──────────────────────────────────────────────

/// Compute the frame offset for a local variable slot.
/// Local slot N is at fp - (N+1)*3.
fn local_frame_offset(slot: u8) -> Result<i8, EmitError> {
    let offset = -((slot as i16 + 1) * WORD as i16);
    if offset < -128 {
        return Err(EmitError::LocalOffsetTooLarge { offset: slot });
    }
    Ok(offset as i8)
}

/// Sign-extend a 24-bit value stored in a u32 to an i32.
fn sign_extend_24(val: u32) -> i32 {
    if val & 0x80_0000 != 0 {
        (val | 0xFF00_0000) as i32
    } else {
        val as i32
    }
}

/// Pre-scan instructions to find all PCs that are branch/jump targets.
fn collect_branch_targets(instructions: &[Instruction]) -> HashSet<u32> {
    let mut targets = HashSet::new();
    for instr in instructions {
        match instr.op {
            Opcode::Jmp | Opcode::Jz | Opcode::Jnz | Opcode::Call | Opcode::Calln => {
                match instr.operand {
                    Operand::Imm24(addr) => {
                        targets.insert(addr);
                    }
                    Operand::D8A24 { addr, .. } => {
                        targets.insert(addr);
                    }
                    _ => {}
                }
            }
            _ => {}
        }
    }
    // Also mark procedure entry points
    for instr in instructions {
        if instr.op == Opcode::Enter {
            targets.insert(instr.pc);
        }
    }
    targets
}

#[cfg(test)]
mod tests {
    use super::*;
    use pcode_model::decode_program;

    /// Build a minimal p24 binary from instructions.
    fn make_p24(instructions: &[u8], global_count: u32) -> Vec<u8> {
        let code_size = instructions.len();
        let mut bin = Vec::new();
        // Header (18 bytes)
        bin.extend_from_slice(&[0x50, 0x32, 0x34, 0x00]); // magic
        bin.push(1); // version
                     // entry point: 0
        bin.push(0);
        bin.push(0);
        bin.push(0);
        // code size (LE24)
        bin.push((code_size & 0xFF) as u8);
        bin.push(((code_size >> 8) & 0xFF) as u8);
        bin.push(((code_size >> 16) & 0xFF) as u8);
        // data size: 0
        bin.push(0);
        bin.push(0);
        bin.push(0);
        // global count (LE24)
        bin.push((global_count & 0xFF) as u8);
        bin.push(((global_count >> 8) & 0xFF) as u8);
        bin.push(((global_count >> 16) & 0xFF) as u8);
        // flags
        bin.push(0);
        // Code segment
        bin.extend_from_slice(instructions);
        bin
    }

    #[test]
    fn emit_push_constant() {
        // push 42, halt
        let code: &[u8] = &[
            0x01, 0x2A, 0x00, 0x00, // push 42
            0x00, // halt
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("lc      r0, 42"));
        assert!(asm.contains("push    r0"));
        assert!(asm.contains("_p24_halt"));
    }

    #[test]
    fn emit_push_large_constant() {
        // push 1000 (0x0003E8)
        let code: &[u8] = &[
            0x01, 0xE8, 0x03, 0x00, // push 1000
            0x00, // halt
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("la      r0, 1000"));
    }

    #[test]
    fn emit_push_negative() {
        // push -1 (0xFFFFFF in 24-bit)
        let code: &[u8] = &[
            0x01, 0xFF, 0xFF, 0xFF, // push -1
            0x00,
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("lc      r0, -1"));
    }

    #[test]
    fn emit_add() {
        // push 3, push 4, add, halt
        let code: &[u8] = &[
            0x01, 0x03, 0x00, 0x00, // push 3
            0x01, 0x04, 0x00, 0x00, // push 4
            0x10, // add
            0x00, // halt
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("add     r0, r1"));
    }

    #[test]
    fn emit_sub() {
        let code: &[u8] = &[
            0x01, 0x0A, 0x00, 0x00, // push 10
            0x01, 0x03, 0x00, 0x00, // push 3
            0x11, // sub (10 - 3 = 7)
            0x00,
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("sub     r1, r0")); // r1=NOS, r0=TOS, r1=NOS-TOS
    }

    #[test]
    fn emit_comparison_eq() {
        let code: &[u8] = &[
            0x01, 0x05, 0x00, 0x00, // push 5
            0x01, 0x05, 0x00, 0x00, // push 5
            0x20, // eq
            0x00,
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("ceq     r1, r0"));
        assert!(asm.contains("mov     r0, c"));
    }

    #[test]
    fn emit_global_load_store() {
        // push 42, storeg 0, loadg 0, halt
        let code: &[u8] = &[
            0x01, 0x2A, 0x00, 0x00, // push 42
            0x45, 0x00, 0x00, 0x00, // storeg 0
            0x44, 0x00, 0x00, 0x00, // loadg 0
            0x00, // halt
        ];
        let bin = make_p24(code, 1);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("_p24_globals"));
        assert!(asm.contains("sw      r0, 0(r1)"));
        assert!(asm.contains("lw      r0, 0(r1)"));
    }

    #[test]
    fn emit_enter_with_locals() {
        // enter 2, push 10, storel 0, loadl 0, halt
        let code: &[u8] = &[
            0x40, 0x02, // enter 2
            0x01, 0x0A, 0x00, 0x00, // push 10
            0x43, 0x00, // storel 0
            0x42, 0x00, // loadl 0
            0x00, // halt
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("push    fp"));
        assert!(asm.contains("mov     fp, sp"));
        assert!(asm.contains("sub     sp, 6")); // 2 locals * 3 bytes
        assert!(asm.contains("-3(fp)")); // local 0 at fp-3
    }

    #[test]
    fn emit_conditional_jump() {
        // push 0, jz target, push 1, halt, target: push 2, halt
        let code: &[u8] = &[
            0x01, 0x00, 0x00, 0x00, // 0000: push 0
            0x31, 0x0D, 0x00, 0x00, // 0004: jz 0x000D
            0x01, 0x01, 0x00, 0x00, // 0008: push 1
            0x00, // 000C: halt
            0x01, 0x02, 0x00, 0x00, // 000D: push 2
            0x00, // 0011: halt
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("ceq     r0, z"));
        assert!(asm.contains("brf     .Lskip0"));
        assert!(asm.contains(".L000D:"));
    }

    #[test]
    fn emit_unconditional_jump() {
        // jmp 0x0004, halt, push 1, halt
        let code: &[u8] = &[
            0x30, 0x08, 0x00, 0x00, // 0000: jmp 0x0008
            0x01, 0x01, 0x00, 0x00, // 0004: push 1 (skipped)
            0x00, // 0008: halt
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("la      r2, .L0008"));
        assert!(asm.contains("jmp     (r2)"));
        assert!(asm.contains(".L0008:"));
    }

    #[test]
    fn emit_neg() {
        let code: &[u8] = &[
            0x01, 0x0A, 0x00, 0x00, // push 10
            0x15, // neg
            0x00,
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("mov     r0, z")); // r0 = 0
        assert!(asm.contains("sub     r0, r1")); // r0 = 0 - TOS
    }

    #[test]
    fn sign_extend_positive() {
        assert_eq!(sign_extend_24(0x00_0001), 1);
        assert_eq!(sign_extend_24(0x7F_FFFF), 8388607);
    }

    #[test]
    fn sign_extend_negative() {
        assert_eq!(sign_extend_24(0xFF_FFFF), -1);
        assert_eq!(sign_extend_24(0x80_0000), -8388608);
    }

    #[test]
    fn emit_full_program_from_p24_file() {
        let bin = std::fs::read(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../tests/p24/arithmetic.p24"
        ));
        if let Ok(bin) = bin {
            let prog = decode_program(&bin).unwrap();
            let asm = emit_program(&prog, "arithmetic.p24").unwrap();
            // Should have prologue, instructions, epilogue
            assert!(asm.contains("Generated by pc-aotc"));
            assert!(asm.contains("la      sp,"));
            assert!(asm.contains("_p24_halt:"));
            // Should contain some of our supported opcodes
            assert!(asm.contains("push    fp")); // from enter
            assert!(asm.contains("_p24_globals")); // globals section
        }
    }
}
