use pcode_model::{Instruction, Opcode, Operand, Program, SysCall, WORD};
use std::collections::{HashMap, HashSet};
use std::fmt::Write;

/// Errors during assembly emission.
#[derive(Debug)]
pub enum EmitError {
    /// A fmt::Write call failed.
    Fmt(std::fmt::Error),
    /// Global variable offset too large for single-instruction access.
    GlobalOffsetTooLarge { addr: u32 },
    /// Local variable offset too large for single-instruction access.
    LocalOffsetTooLarge { offset: u8 },
    /// Argument access without known nargs for the containing procedure.
    UnknownNargs { pc: u32 },
}

impl std::fmt::Display for EmitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EmitError::Fmt(e) => write!(f, "format error: {e}"),
            EmitError::GlobalOffsetTooLarge { addr } => {
                write!(f, "global offset too large: {addr} (max 42)")
            }
            EmitError::LocalOffsetTooLarge { offset } => {
                write!(f, "local offset too large: {offset} (max 41)")
            }
            EmitError::UnknownNargs { pc } => {
                write!(
                    f,
                    "loada/storea at PC=0x{pc:04X} but containing procedure has unknown nargs"
                )
            }
        }
    }
}

impl std::error::Error for EmitError {}

impl From<std::fmt::Error> for EmitError {
    fn from(e: std::fmt::Error) -> Self {
        EmitError::Fmt(e)
    }
}

/// Initial stack pointer address. Programs start with sp set here;
/// the stack grows downward from this address.
const STACK_TOP: u32 = 0x2000;

/// Frame header size in bytes: return address (3) + old fp (3).
const FRAME_HEADER: usize = 6;

/// Emit COR24 assembly for a decoded p-code program.
///
/// Returns the complete assembly text as a string, ready to be written
/// to a `.s` file and assembled by the COR24 cross-assembler (as24).
pub fn emit_program(program: &Program, source_name: &str) -> Result<String, EmitError> {
    let mut e = Emitter::new(program);
    e.prologue(program, source_name)?;
    for instr in &program.instructions {
        e.instruction(instr)?;
    }
    e.epilogue(program)?;
    Ok(e.out)
}

// ── Emitter ────────────────────────────────────────────────────────

struct Emitter {
    out: String,
    /// P-code PCs that are jump/branch targets and need labels.
    targets: HashSet<u32>,
    /// Counter for generating unique skip labels (for conditional branches).
    skip_id: u32,
    /// Map from procedure entry PC to procedure info (nargs, num_locals).
    proc_info: HashMap<u32, ProcInfo>,
    /// Current procedure's info (set when we encounter an `enter`).
    current_proc: Option<ProcInfo>,
    /// Whether the _p24_divmod helper is needed.
    needs_divmod: bool,
}

/// Minimal procedure info carried by the emitter.
#[derive(Debug, Clone, Copy)]
struct ProcInfo {
    nargs: u8,
    num_locals: u8,
}

impl Emitter {
    fn new(program: &Program) -> Self {
        let mut proc_info = HashMap::new();
        for p in &program.procedures {
            proc_info.insert(
                p.entry_pc,
                ProcInfo {
                    nargs: p.nargs.unwrap_or(0),
                    num_locals: p.num_locals,
                },
            );
        }
        Self {
            out: String::with_capacity(8192),
            targets: collect_branch_targets(&program.instructions),
            skip_id: 0,
            proc_info,
            current_proc: None,
            needs_divmod: false,
        }
    }

    fn next_skip(&mut self) -> u32 {
        let id = self.skip_id;
        self.skip_id += 1;
        id
    }

    // ── Prologue / epilogue ────────────────────────────────────────

    fn prologue(&mut self, program: &Program, source_name: &str) -> Result<(), EmitError> {
        writeln!(self.out, "; Generated by pc-aotc from {source_name}")?;
        writeln!(self.out, "; COR24 p-code AOT compiler output")?;
        writeln!(self.out)?;
        writeln!(self.out, "    la      r0, {STACK_TOP}")?;
        writeln!(self.out, "    mov     sp, r0")?;
        if program.entry_point != 0 {
            writeln!(self.out, "    la      r2, .L{:04X}", program.entry_point)?;
            writeln!(self.out, "    jmp     (r2)")?;
        }
        writeln!(self.out)?;
        Ok(())
    }

    fn epilogue(&mut self, program: &Program) -> Result<(), EmitError> {
        // Halt loop (target for halt opcode)
        writeln!(self.out, "_p24_halt:")?;
        writeln!(self.out, "    bra     _p24_halt")?;
        writeln!(self.out)?;

        // Emit divmod helper if needed
        if self.needs_divmod {
            self.emit_divmod_helper()?;
        }

        // Global variable storage
        if program.global_count > 0 {
            let size = program.global_count as usize * WORD;
            writeln!(
                self.out,
                "; Global variables ({} words)",
                program.global_count
            )?;
            writeln!(self.out, "_p24_globals:")?;
            // Emit zero-initialized bytes
            for _ in 0..size {
                writeln!(self.out, "    .byte   0")?;
            }
            writeln!(self.out)?;
        }

        // Data segment (if any)
        if !program.data.is_empty() {
            writeln!(self.out, "; Data segment ({} bytes)", program.data.len())?;
            writeln!(self.out, "_p24_data:")?;
            for chunk in program.data.chunks(16) {
                let bytes: Vec<String> = chunk.iter().map(|b| format!("{b}")).collect();
                writeln!(self.out, "    .byte   {}", bytes.join(","))?;
            }
            writeln!(self.out)?;
        }

        Ok(())
    }

    // ── Instruction dispatch ───────────────────────────────────────

    fn instruction(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        // Emit label if this PC is a branch target or procedure entry
        if self.targets.contains(&instr.pc) {
            writeln!(self.out, ".L{:04X}:", instr.pc)?;
        }

        // Track current procedure when we see enter
        if instr.op == Opcode::Enter {
            self.current_proc = self.proc_info.get(&instr.pc).copied();
        }

        // Comment with p-code disassembly
        self.pcode_comment(instr)?;

        match instr.op {
            // Stack operations
            Opcode::Halt => self.op_halt()?,
            Opcode::Push => self.op_push(instr)?,
            Opcode::PushS => self.op_push_s(instr)?,
            Opcode::Dup => self.op_dup()?,
            Opcode::Drop => self.op_drop()?,
            Opcode::Swap => self.op_swap()?,
            Opcode::Over => self.op_over()?,

            // Arithmetic
            Opcode::Add => self.op_commutative_binop("add")?,
            Opcode::Sub => self.op_sub()?,
            Opcode::Mul => self.op_commutative_binop("mul")?,
            Opcode::Div => self.op_div()?,
            Opcode::Mod => self.op_mod()?,
            Opcode::Neg => self.op_neg()?,

            // Bitwise
            Opcode::And => self.op_commutative_binop("and")?,
            Opcode::Or => self.op_commutative_binop("or")?,
            Opcode::Xor => self.op_commutative_binop("xor")?,
            Opcode::Not => self.op_not()?,
            Opcode::Shl => self.op_shift("shl")?,
            Opcode::Shr => self.op_shift("sra")?,

            // Comparisons
            Opcode::Eq => self.op_eq()?,
            Opcode::Ne => self.op_ne()?,
            Opcode::Lt => self.op_lt()?,
            Opcode::Le => self.op_le()?,
            Opcode::Gt => self.op_gt()?,
            Opcode::Ge => self.op_ge()?,

            // Control flow
            Opcode::Jmp => self.op_jmp(instr)?,
            Opcode::Jz => self.op_jz(instr)?,
            Opcode::Jnz => self.op_jnz(instr)?,
            Opcode::Call => self.op_call(instr)?,
            Opcode::Calln => self.op_calln(instr)?,
            Opcode::Ret => self.op_ret(instr)?,
            Opcode::Trap => self.op_trap(instr)?,

            // Frame / variable access
            Opcode::Enter => self.op_enter(instr)?,
            Opcode::Leave => self.op_leave()?,
            Opcode::Loadl => self.op_loadl(instr)?,
            Opcode::Storel => self.op_storel(instr)?,
            Opcode::Loadg => self.op_loadg(instr)?,
            Opcode::Storeg => self.op_storeg(instr)?,
            Opcode::Loada => self.op_loada(instr)?,
            Opcode::Storea => self.op_storea(instr)?,

            // Address-of operations
            Opcode::Addrl => self.op_addrl(instr)?,
            Opcode::Addrg => self.op_addrg(instr)?,

            // Indirect memory access
            Opcode::Load => self.op_load()?,
            Opcode::Store => self.op_store()?,
            Opcode::Loadb => self.op_loadb()?,
            Opcode::Storeb => self.op_storeb()?,

            // Memory block operations
            Opcode::Memcpy => self.op_memcpy()?,
            Opcode::Memset => self.op_memset()?,

            // Nonlocal variable access
            Opcode::Loadn => self.op_loadn(instr)?,
            Opcode::Storen => self.op_storen(instr)?,

            // System calls
            Opcode::Sys => self.op_sys(instr)?,
        }
        writeln!(self.out)?;
        Ok(())
    }

    // ── Stack operations ───────────────────────────────────────────

    fn op_halt(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    la      r2, _p24_halt")?;
        writeln!(self.out, "    jmp     (r2)")?;
        Ok(())
    }

    fn op_push(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm24(val) = instr.operand {
            let sval = sign_extend_24(val);
            self.load_immediate("r0", sval)?;
            writeln!(self.out, "    push    r0")?;
        }
        Ok(())
    }

    fn op_push_s(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm8(val) = instr.operand {
            let sval = val as i8 as i32;
            self.load_immediate("r0", sval)?;
            writeln!(self.out, "    push    r0")?;
        }
        Ok(())
    }

    fn op_dup(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    mov     r0, sp")?;
        writeln!(self.out, "    lw      r0, 0(r0)")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    fn op_drop(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?;
        Ok(())
    }

    fn op_swap(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?;
        writeln!(self.out, "    pop     r1")?;
        writeln!(self.out, "    push    r0")?;
        writeln!(self.out, "    push    r1")?;
        Ok(())
    }

    fn op_over(&mut self) -> Result<(), EmitError> {
        // NOS is one word below TOS: sp+3
        writeln!(self.out, "    mov     r0, sp")?;
        writeln!(self.out, "    lw      r0, 3(r0)")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    // ── Arithmetic ─────────────────────────────────────────────────

    /// Emit a commutative binary op (add, mul, and, or, xor): pop two, compute, push result.
    fn op_commutative_binop(&mut self, mnemonic: &str) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?; // TOS
        writeln!(self.out, "    pop     r1")?; // NOS
        writeln!(self.out, "    {mnemonic:<8}r0, r1")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    /// Sub: NOS - TOS. Non-commutative, so operand order matters.
    fn op_sub(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?; // TOS
        writeln!(self.out, "    pop     r1")?; // NOS
        writeln!(self.out, "    sub     r1, r0")?; // r1 = NOS - TOS
        writeln!(self.out, "    push    r1")?;
        Ok(())
    }

    /// Neg: -TOS. COR24 has no neg instruction, so compute 0 - TOS.
    fn op_neg(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r1")?; // TOS
        writeln!(self.out, "    mov     r0, z")?; // r0 = 0
        writeln!(self.out, "    sub     r0, r1")?; // r0 = 0 - TOS
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    /// Not: ~TOS (bitwise complement). Compute TOS XOR 0xFFFFFF.
    fn op_not(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?;
        writeln!(self.out, "    la      r1, -1")?; // 0xFFFFFF
        writeln!(self.out, "    xor     r0, r1")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    /// Shift: shl or sra (arithmetic shift right). NOS shifted by TOS amount.
    fn op_shift(&mut self, mnemonic: &str) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r1")?; // TOS = shift amount
        writeln!(self.out, "    pop     r0")?; // NOS = value
        writeln!(self.out, "    {mnemonic:<8}r0, r1")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    /// Div: NOS / TOS (signed integer division). Calls _p24_divmod helper.
    /// _p24_divmod: r0=dividend, r1=divisor, return addr on stack.
    /// Returns: r0=quotient, r1=remainder.
    fn op_div(&mut self) -> Result<(), EmitError> {
        self.needs_divmod = true;
        let skip = self.next_skip();
        writeln!(self.out, "    pop     r1")?; // TOS = divisor
        writeln!(self.out, "    pop     r0")?; // NOS = dividend
        writeln!(self.out, "    la      r2, .Ldiv_ret{skip}")?;
        writeln!(self.out, "    push    r2")?; // push return address
        writeln!(self.out, "    la      r2, _p24_divmod")?;
        writeln!(self.out, "    jmp     (r2)")?;
        writeln!(self.out, ".Ldiv_ret{skip}:")?;
        writeln!(self.out, "    push    r0")?; // push quotient
        Ok(())
    }

    /// Mod: NOS % TOS (signed modulo). Calls _p24_divmod helper.
    fn op_mod(&mut self) -> Result<(), EmitError> {
        self.needs_divmod = true;
        let skip = self.next_skip();
        writeln!(self.out, "    pop     r1")?; // TOS = divisor
        writeln!(self.out, "    pop     r0")?; // NOS = dividend
        writeln!(self.out, "    la      r2, .Lmod_ret{skip}")?;
        writeln!(self.out, "    push    r2")?; // push return address
        writeln!(self.out, "    la      r2, _p24_divmod")?;
        writeln!(self.out, "    jmp     (r2)")?;
        writeln!(self.out, ".Lmod_ret{skip}:")?;
        writeln!(self.out, "    push    r1")?; // push remainder
        Ok(())
    }

    // ── Comparisons ────────────────────────────────────────────────
    //
    // COR24 has: ceq (==), cls (signed <), clu (unsigned <).
    // The condition flag C is read via `mov rX, c`.
    // For ne/le/ge we compute the inverse by checking if C == 0.

    /// Eq: NOS == TOS → 1, else 0.
    fn op_eq(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?; // TOS
        writeln!(self.out, "    pop     r1")?; // NOS
        writeln!(self.out, "    ceq     r0, r1")?; // C = (TOS == NOS), symmetric
        writeln!(self.out, "    mov     r0, c")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    /// Ne: NOS != TOS → 1, else 0. Invert eq result.
    fn op_ne(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?;
        writeln!(self.out, "    pop     r1")?;
        writeln!(self.out, "    ceq     r0, r1")?; // C = (TOS == NOS), symmetric
        writeln!(self.out, "    mov     r0, c")?; // r0 = eq result
        writeln!(self.out, "    ceq     r0, z")?; // C = (r0 == 0) = not-equal
        writeln!(self.out, "    mov     r0, c")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    /// Lt: NOS < TOS (signed) → 1, else 0.
    fn op_lt(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?; // TOS
        writeln!(self.out, "    pop     r1")?; // NOS
        writeln!(self.out, "    cls     r1, r0")?; // C = (NOS < TOS)
        writeln!(self.out, "    mov     r0, c")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    /// Le: NOS <= TOS ⟺ ¬(TOS < NOS).
    fn op_le(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?; // TOS
        writeln!(self.out, "    pop     r1")?; // NOS
        writeln!(self.out, "    cls     r0, r1")?; // C = (TOS < NOS)
        writeln!(self.out, "    mov     r0, c")?; // r0 = (TOS < NOS)
        writeln!(self.out, "    ceq     r0, z")?; // C = ¬(TOS < NOS) = (NOS <= TOS)
        writeln!(self.out, "    mov     r0, c")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    /// Gt: NOS > TOS ⟺ TOS < NOS.
    fn op_gt(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?; // TOS
        writeln!(self.out, "    pop     r1")?; // NOS
        writeln!(self.out, "    cls     r0, r1")?; // C = (TOS < NOS) = (NOS > TOS)
        writeln!(self.out, "    mov     r0, c")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    /// Ge: NOS >= TOS ⟺ ¬(NOS < TOS).
    fn op_ge(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r0")?; // TOS
        writeln!(self.out, "    pop     r1")?; // NOS
        writeln!(self.out, "    cls     r1, r0")?; // C = (NOS < TOS)
        writeln!(self.out, "    mov     r0, c")?; // r0 = (NOS < TOS)
        writeln!(self.out, "    ceq     r0, z")?; // C = ¬(NOS < TOS) = (NOS >= TOS)
        writeln!(self.out, "    mov     r0, c")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    // ── Control flow ───────────────────────────────────────────────

    /// Unconditional jump. Uses absolute addressing via la + jmp.
    fn op_jmp(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm24(addr) = instr.operand {
            writeln!(self.out, "    la      r2, .L{addr:04X}")?;
            writeln!(self.out, "    jmp     (r2)")?;
        }
        Ok(())
    }

    /// Jump if zero: pop TOS, branch to target if TOS == 0.
    fn op_jz(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm24(addr) = instr.operand {
            let skip = self.next_skip();
            writeln!(self.out, "    pop     r0")?;
            writeln!(self.out, "    ceq     r0, z")?; // C = (TOS == 0)
            writeln!(self.out, "    brf     .Lskip{skip}")?; // skip if not zero
            writeln!(self.out, "    la      r2, .L{addr:04X}")?;
            writeln!(self.out, "    jmp     (r2)")?;
            writeln!(self.out, ".Lskip{skip}:")?;
        }
        Ok(())
    }

    /// Jump if non-zero: pop TOS, branch to target if TOS != 0.
    fn op_jnz(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm24(addr) = instr.operand {
            let skip = self.next_skip();
            writeln!(self.out, "    pop     r0")?;
            writeln!(self.out, "    ceq     r0, z")?; // C = (TOS == 0)
            writeln!(self.out, "    brt     .Lskip{skip}")?; // skip if zero
            writeln!(self.out, "    la      r2, .L{addr:04X}")?;
            writeln!(self.out, "    jmp     (r2)")?;
            writeln!(self.out, ".Lskip{skip}:")?;
        }
        Ok(())
    }

    /// Call procedure (flat call, no static link depth).
    ///
    /// Uses `jal r1, (r2)` to set r1 = return address and jump.
    /// The callee's `enter` will save r1 as part of the frame header.
    fn op_call(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm24(addr) = instr.operand {
            writeln!(self.out, "    la      r2, .L{addr:04X}")?;
            writeln!(self.out, "    jal     r1, (r2)")?;
        }
        Ok(())
    }

    /// Call with explicit static link depth (for nested procedures).
    /// Currently emits the same as flat call (static link not yet used).
    fn op_calln(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::D8A24 { addr, .. } = instr.operand {
            writeln!(self.out, "    la      r2, .L{addr:04X}")?;
            writeln!(self.out, "    jal     r1, (r2)")?;
        }
        Ok(())
    }

    /// Return from procedure, clean nargs.
    ///
    /// Frame layout (stack grows down):
    /// ```text
    ///     [argN-1]  ← fp + 6
    ///     ...
    ///     [arg0]    ← fp + 6 + (nargs-1)*3
    ///     [ret_addr] ← fp + 3
    ///     [old_fp]   ← fp + 0
    ///     [local0]   ← fp - 3
    ///     ...
    ///     [eval...]  ← sp
    /// ```
    ///
    /// For procedures (no return value): discard frame and args, jump back.
    /// For functions: save TOS (return value) in r0, restore, push back.
    fn op_ret(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm8(nargs) = instr.operand {
            // Detect if there's a return value by checking if eval stack
            // is non-empty relative to locals. We use a dynamic check:
            // if sp < fp - num_locals*3, there's something on the eval stack.
            let num_locals = self.current_proc.map(|p| p.num_locals).unwrap_or(0);
            let locals_bytes = num_locals as i32 * WORD as i32;

            let skip = self.next_skip();

            // r2 = fp - locals_bytes = bottom of locals (expected empty sp)
            writeln!(self.out, "    push    fp")?;
            writeln!(self.out, "    pop     r2")?;
            if locals_bytes > 0 {
                writeln!(self.out, "    add     r2, -{locals_bytes}")?;
            }
            // Compare: is sp below the expected empty position?
            // If sp < r2, there's a return value on the eval stack.
            // COR24: cls sets C = (ra < rb) signed
            // But we can't use sp directly in cls. Copy sp to r0.
            writeln!(self.out, "    mov     r0, sp")?;
            writeln!(self.out, "    cls     r0, r2")?; // C = (sp < expected)
            writeln!(self.out, "    brf     .Lret_noval{skip}")?; // skip if no retval

            // Has return value: save it
            writeln!(self.out, "    pop     r0")?; // r0 = return value
            writeln!(self.out, "    mov     sp, fp")?; // discard locals
            writeln!(self.out, "    pop     fp")?; // restore fp
            writeln!(self.out, "    pop     r2")?; // r2 = return address
            if nargs > 0 {
                let arg_bytes = nargs as u32 * WORD as u32;
                writeln!(self.out, "    add     sp, {arg_bytes}")?;
            }
            writeln!(self.out, "    push    r0")?; // push return value
            writeln!(self.out, "    jmp     (r2)")?; // return

            // No return value path
            writeln!(self.out, ".Lret_noval{skip}:")?;
            writeln!(self.out, "    mov     sp, fp")?;
            writeln!(self.out, "    pop     fp")?;
            writeln!(self.out, "    pop     r2")?;
            if nargs > 0 {
                let arg_bytes = nargs as u32 * WORD as u32;
                writeln!(self.out, "    add     sp, {arg_bytes}")?;
            }
            writeln!(self.out, "    jmp     (r2)")?;
        }
        Ok(())
    }

    /// Trap: enter halt loop (simplified — full trap handling is future work).
    fn op_trap(&mut self, _instr: &Instruction) -> Result<(), EmitError> {
        writeln!(self.out, "    la      r2, _p24_halt")?;
        writeln!(self.out, "    jmp     (r2)")?;
        Ok(())
    }

    // ── Frame / variable access ────────────────────────────────────

    /// Enter: set up activation frame, allocate local variable slots.
    ///
    /// Saves r1 (return address from `jal`) and old fp, then sets fp and
    /// allocates locals.
    ///
    /// Frame layout (stack grows downward):
    /// ```text
    ///     [ret_addr]  ← fp + 3  (r1 from jal, or garbage for main)
    ///     [old_fp]    ← fp + 0
    ///     [local 0]   ← fp - 3
    ///     [local 1]   ← fp - 6
    ///     ...
    ///     [local N-1] ← fp - N*3
    ///     [eval stack] ← sp (current top)
    /// ```
    fn op_enter(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm8(nlocals) = instr.operand {
            writeln!(self.out, "    push    r1")?; // save return address
            writeln!(self.out, "    push    fp")?; // save old frame pointer
            writeln!(self.out, "    mov     fp, sp")?;
            if nlocals > 0 {
                let size = nlocals as u32 * WORD as u32;
                writeln!(self.out, "    sub     sp, {size}")?;
            }
        }
        Ok(())
    }

    /// Leave: tear down activation frame (inverse of enter).
    /// In practice, `leave` is dead code after `ret` in p-code programs.
    /// It's emitted for completeness but typically never reached.
    fn op_leave(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    mov     sp, fp")?;
        writeln!(self.out, "    pop     fp")?;
        writeln!(self.out, "    pop     r1")?; // discard saved return address
        Ok(())
    }

    /// Load local variable at slot offset onto eval stack.
    fn op_loadl(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm8(slot) = instr.operand {
            let offset = local_frame_offset(slot)?;
            writeln!(self.out, "    lw      r0, {offset}(fp)")?;
            writeln!(self.out, "    push    r0")?;
        }
        Ok(())
    }

    /// Store TOS into local variable at slot offset.
    fn op_storel(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm8(slot) = instr.operand {
            let offset = local_frame_offset(slot)?;
            writeln!(self.out, "    pop     r0")?;
            writeln!(self.out, "    sw      r0, {offset}(fp)")?;
        }
        Ok(())
    }

    /// Load global variable onto eval stack.
    fn op_loadg(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm24(addr) = instr.operand {
            let byte_offset = addr as usize * WORD;
            writeln!(self.out, "    la      r1, _p24_globals")?;
            if byte_offset <= 127 {
                writeln!(self.out, "    lw      r0, {byte_offset}(r1)")?;
            } else {
                writeln!(self.out, "    la      r2, {byte_offset}")?;
                writeln!(self.out, "    add     r1, r2")?;
                writeln!(self.out, "    lw      r0, 0(r1)")?;
            }
            writeln!(self.out, "    push    r0")?;
        }
        Ok(())
    }

    /// Store TOS into global variable.
    fn op_storeg(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm24(addr) = instr.operand {
            let byte_offset = addr as usize * WORD;
            writeln!(self.out, "    pop     r0")?;
            writeln!(self.out, "    la      r1, _p24_globals")?;
            if byte_offset <= 127 {
                writeln!(self.out, "    sw      r0, {byte_offset}(r1)")?;
            } else {
                writeln!(self.out, "    la      r2, {byte_offset}")?;
                writeln!(self.out, "    add     r1, r2")?;
                writeln!(self.out, "    sw      r0, 0(r1)")?;
            }
        }
        Ok(())
    }

    /// Load argument at index onto eval stack.
    ///
    /// Arguments are above the frame header on the stack:
    /// `arg[idx]` is at `fp + FRAME_HEADER + (nargs - 1 - idx) * 3`.
    fn op_loada(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm8(idx) = instr.operand {
            let nargs = self
                .current_proc
                .map(|p| p.nargs)
                .ok_or(EmitError::UnknownNargs { pc: instr.pc })?;
            let offset = arg_frame_offset(nargs, idx);
            writeln!(self.out, "    lw      r0, {offset}(fp)")?;
            writeln!(self.out, "    push    r0")?;
        }
        Ok(())
    }

    /// Store TOS into argument at index.
    fn op_storea(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm8(idx) = instr.operand {
            let nargs = self
                .current_proc
                .map(|p| p.nargs)
                .ok_or(EmitError::UnknownNargs { pc: instr.pc })?;
            let offset = arg_frame_offset(nargs, idx);
            writeln!(self.out, "    pop     r0")?;
            writeln!(self.out, "    sw      r0, {offset}(fp)")?;
        }
        Ok(())
    }

    // ── Address-of operations ──────────────────────────────────────

    /// Push address of local variable at slot offset.
    fn op_addrl(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm8(slot) = instr.operand {
            let offset = local_frame_offset(slot)?;
            // addr = fp + offset (offset is negative)
            // COR24: can't mov r0,fp directly; use push/pop
            writeln!(self.out, "    push    fp")?;
            writeln!(self.out, "    pop     r0")?;
            writeln!(self.out, "    add     r0, {offset}")?;
            writeln!(self.out, "    push    r0")?;
        }
        Ok(())
    }

    /// Push address of global variable at word offset.
    fn op_addrg(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm24(addr) = instr.operand {
            let byte_offset = addr as usize * WORD;
            writeln!(self.out, "    la      r0, _p24_globals")?;
            if byte_offset > 0 {
                if byte_offset <= 127 {
                    writeln!(self.out, "    add     r0, {byte_offset}")?;
                } else {
                    writeln!(self.out, "    la      r1, {byte_offset}")?;
                    writeln!(self.out, "    add     r0, r1")?;
                }
            }
            writeln!(self.out, "    push    r0")?;
        }
        Ok(())
    }

    // ── Indirect memory access ─────────────────────────────────────

    /// Load word from address on stack. ( addr -- val )
    fn op_load(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r1")?; // addr
        writeln!(self.out, "    lw      r0, 0(r1)")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    /// Store word to address on stack. ( val addr -- )
    fn op_store(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r1")?; // addr
        writeln!(self.out, "    pop     r0")?; // val
        writeln!(self.out, "    sw      r0, 0(r1)")?;
        Ok(())
    }

    /// Load byte (zero-extended) from address. ( addr -- byte )
    fn op_loadb(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r1")?; // addr
        writeln!(self.out, "    lbu     r0, 0(r1)")?;
        writeln!(self.out, "    push    r0")?;
        Ok(())
    }

    /// Store byte to address. ( byte addr -- )
    fn op_storeb(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "    pop     r1")?; // addr
        writeln!(self.out, "    pop     r0")?; // byte
        writeln!(self.out, "    sb      r0, 0(r1)")?;
        Ok(())
    }

    // ── Memory block operations ───────────────────────────────────

    /// Memcpy: copy len bytes from src to dst (memmove semantics). ( src dst len -- )
    ///
    /// Inlined loop using r0=scratch/len, r1=dst, r2=src.
    /// Len counter kept on the stack during the loop.
    fn op_memcpy(&mut self) -> Result<(), EmitError> {
        let skip = self.next_skip();
        writeln!(self.out, "    pop     r0")?; // len
        writeln!(self.out, "    pop     r1")?; // dst
        writeln!(self.out, "    pop     r2")?; // src
                                               // If len==0, skip
        writeln!(self.out, "    ceq     r0, z")?;
        writeln!(self.out, "    brt     .Lmcp_done{skip}")?;
        // Direction check: if src < dst, copy backward (memmove semantics)
        writeln!(self.out, "    push    r0")?; // save len on stack
        writeln!(self.out, "    clu     r2, r1")?; // C = (src < dst)
        writeln!(self.out, "    brt     .Lmcp_bwd{skip}")?;
        // Forward copy
        writeln!(self.out, ".Lmcp_fwd{skip}:")?;
        writeln!(self.out, "    pop     r0")?; // remaining len
        writeln!(self.out, "    ceq     r0, z")?;
        writeln!(self.out, "    brt     .Lmcp_done{skip}")?;
        writeln!(self.out, "    add     r0, -1")?;
        writeln!(self.out, "    push    r0")?; // save remaining
        writeln!(self.out, "    lbu     r0, 0(r2)")?; // byte from src
        writeln!(self.out, "    sb      r0, 0(r1)")?; // byte to dst
        writeln!(self.out, "    add     r2, 1")?; // src++
        writeln!(self.out, "    add     r1, 1")?; // dst++
        writeln!(self.out, "    bra     .Lmcp_fwd{skip}")?;
        // Backward copy: start from end
        writeln!(self.out, ".Lmcp_bwd{skip}:")?;
        writeln!(self.out, "    pop     r0")?; // len
        writeln!(self.out, "    add     r0, -1")?; // len-1
        writeln!(self.out, "    add     r2, r0")?; // src += len-1
        writeln!(self.out, "    add     r1, r0")?; // dst += len-1
        writeln!(self.out, "    add     r0, 1")?; // restore len
        writeln!(self.out, "    push    r0")?; // save len
        writeln!(self.out, ".Lmcp_bloop{skip}:")?;
        writeln!(self.out, "    pop     r0")?;
        writeln!(self.out, "    ceq     r0, z")?;
        writeln!(self.out, "    brt     .Lmcp_done{skip}")?;
        writeln!(self.out, "    add     r0, -1")?;
        writeln!(self.out, "    push    r0")?;
        writeln!(self.out, "    lbu     r0, 0(r2)")?;
        writeln!(self.out, "    sb      r0, 0(r1)")?;
        writeln!(self.out, "    add     r2, -1")?; // src--
        writeln!(self.out, "    add     r1, -1")?; // dst--
        writeln!(self.out, "    bra     .Lmcp_bloop{skip}")?;
        writeln!(self.out, ".Lmcp_done{skip}:")?;
        Ok(())
    }

    /// Memset: fill len bytes at dst with byte value. ( dst val len -- )
    ///
    /// Inlined loop using r0=len, r1=val, r2=dst.
    fn op_memset(&mut self) -> Result<(), EmitError> {
        let skip = self.next_skip();
        writeln!(self.out, "    pop     r0")?; // len
        writeln!(self.out, "    pop     r1")?; // val
        writeln!(self.out, "    pop     r2")?; // dst
        writeln!(self.out, "    ceq     r0, z")?;
        writeln!(self.out, "    brt     .Lms_done{skip}")?;
        writeln!(self.out, ".Lms_loop{skip}:")?;
        writeln!(self.out, "    sb      r1, 0(r2)")?; // *dst = val
        writeln!(self.out, "    add     r2, 1")?; // dst++
        writeln!(self.out, "    add     r0, -1")?; // len--
        writeln!(self.out, "    ceq     r0, z")?;
        writeln!(self.out, "    brf     .Lms_loop{skip}")?; // branch if len != 0
        writeln!(self.out, ".Lms_done{skip}:")?;
        Ok(())
    }

    // ── Nonlocal variable access ──────────────────────────────────

    /// Load nonlocal variable via static link chain. ( -- val )
    ///
    /// Follows the static link `depth` times from the current frame,
    /// then loads the local at `offset` in the target frame.
    fn op_loadn(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::D8O8 { depth, offset } = instr.operand {
            // Start at current frame pointer (can't mov r0,fp directly)
            writeln!(self.out, "    push    fp")?;
            writeln!(self.out, "    pop     r0")?;
            // Follow static link chain `depth` times
            // Static link is at fp + 0 (old_fp) which is the dynamic link.
            for _ in 0..depth {
                writeln!(self.out, "    lw      r0, 0(r0)")?; // follow old_fp
            }
            // Load local at offset in target frame
            let byte_offset = local_frame_offset(offset)?;
            writeln!(self.out, "    lw      r0, {byte_offset}(r0)")?;
            writeln!(self.out, "    push    r0")?;
        }
        Ok(())
    }

    /// Store nonlocal variable via static link chain. ( val -- )
    fn op_storen(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::D8O8 { depth, offset } = instr.operand {
            writeln!(self.out, "    pop     r0")?; // val
                                                   // Start at current frame pointer (can't mov r1,fp directly)
            writeln!(self.out, "    push    fp")?;
            writeln!(self.out, "    pop     r1")?;
            // Follow static link chain
            for _ in 0..depth {
                writeln!(self.out, "    lw      r1, 0(r1)")?; // follow old_fp
            }
            // Store to local at offset in target frame
            let byte_offset = local_frame_offset(offset)?;
            writeln!(self.out, "    sw      r0, {byte_offset}(r1)")?;
        }
        Ok(())
    }

    // ── System calls ───────────────────────────────────────────────

    fn op_sys(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        if let Operand::Imm8(id) = instr.operand {
            match SysCall::from_id(id) {
                Some(SysCall::Halt) => {
                    writeln!(self.out, "    la      r2, _p24_halt")?;
                    writeln!(self.out, "    jmp     (r2)")?;
                }
                Some(SysCall::Putc) => {
                    let skip = self.next_skip();
                    writeln!(self.out, "    pop     r0")?; // char to write
                    writeln!(self.out, "    la      r1, 0xFF0100")?; // UART base
                    writeln!(self.out, ".Lputc{skip}:")?;
                    writeln!(self.out, "    lb      r2, 1(r1)")?; // read status
                    writeln!(self.out, "    cls     r2, z")?; // C = (status < 0) = TX busy
                    writeln!(self.out, "    brt     .Lputc{skip}")?; // wait if busy
                    writeln!(self.out, "    sb      r0, 0(r1)")?; // write char
                }
                Some(SysCall::Getc) => {
                    let skip = self.next_skip();
                    writeln!(self.out, "    la      r1, 0xFF0100")?; // UART base
                    writeln!(self.out, ".Lgetc{skip}:")?;
                    writeln!(self.out, "    lbu     r2, 1(r1)")?; // read status (unsigned)
                    writeln!(self.out, "    lc      r0, 1")?; // RX ready mask
                    writeln!(self.out, "    and     r2, r0")?; // isolate bit 0
                    writeln!(self.out, "    ceq     r2, z")?; // C = (no data)
                    writeln!(self.out, "    brt     .Lgetc{skip}")?; // wait if not ready
                    writeln!(self.out, "    lbu     r0, 0(r1)")?; // read char
                    writeln!(self.out, "    push    r0")?;
                }
                _ => {
                    writeln!(self.out, "    ; TODO: unsupported sys call {id}")?;
                }
            }
        }
        Ok(())
    }

    // ── Helpers ────────────────────────────────────────────────────

    /// Emit a p-code disassembly comment line.
    fn pcode_comment(&mut self, instr: &Instruction) -> Result<(), EmitError> {
        writeln!(self.out, "    ; {instr}")?;
        Ok(())
    }

    /// Emit instructions to load an immediate value into a register.
    /// Chooses the smallest encoding: lc (8-bit signed), lcu (8-bit unsigned), or la (24-bit).
    fn load_immediate(&mut self, reg: &str, val: i32) -> Result<(), EmitError> {
        if (-128..=127).contains(&val) {
            writeln!(self.out, "    lc      {reg}, {val}")?;
        } else if (0..=255).contains(&val) {
            writeln!(self.out, "    lcu     {reg}, {val}")?;
        } else {
            writeln!(self.out, "    la      {reg}, {val}")?;
        }
        Ok(())
    }

    /// Emit the signed integer division/modulo helper routine.
    ///
    /// Entry: r0 = dividend, r1 = divisor
    /// Exit:  r0 = quotient, r1 = remainder
    /// Uses:  r2 as scratch, hardware stack for temporaries
    /// Link:  returns via `jmp (r2)` where r2 was set by inline return label
    ///
    /// Algorithm: repeated subtraction with sign handling.
    /// For correctness: quotient truncates toward zero, remainder has sign of dividend.
    fn emit_divmod_helper(&mut self) -> Result<(), EmitError> {
        writeln!(self.out, "; Signed integer division/modulo helper")?;
        writeln!(self.out, "; Entry: r0 = dividend, r1 = divisor")?;
        writeln!(self.out, "; Exit:  r0 = quotient, r1 = remainder")?;
        writeln!(self.out, "; Link:  pop return address from stack, jmp (r2)")?;
        writeln!(self.out, "_p24_divmod:")?;

        // Trap on division by zero
        writeln!(self.out, "    ceq     r1, z")?;
        writeln!(self.out, "    brf     .Ldm_ok")?;
        writeln!(self.out, "    la      r2, _p24_halt")?;
        writeln!(self.out, "    jmp     (r2)")?;
        writeln!(self.out, ".Ldm_ok:")?;

        // Save signs. We'll compute |dividend| / |divisor| then fix signs.
        // Push sign flags: bit pattern where bit 0 = negate quotient
        writeln!(self.out, "    push    r0")?; // save dividend for sign check later
        writeln!(self.out, "    push    r1")?; // save divisor for sign check later

        // Make dividend positive
        writeln!(self.out, "    cls     r0, z")?; // C = (dividend < 0)
        writeln!(self.out, "    brf     .Ldm_dpos")?;
        writeln!(self.out, "    mov     r2, z")?;
        writeln!(self.out, "    sub     r2, r0")?;
        writeln!(self.out, "    mov     r0, r2")?; // r0 = |dividend|
        writeln!(self.out, ".Ldm_dpos:")?;

        // Make divisor positive
        writeln!(self.out, "    cls     r1, z")?; // C = (divisor < 0)
        writeln!(self.out, "    brf     .Ldm_vpos")?;
        writeln!(self.out, "    mov     r2, z")?;
        writeln!(self.out, "    sub     r2, r1")?;
        writeln!(self.out, "    mov     r1, r2")?; // r1 = |divisor|
        writeln!(self.out, ".Ldm_vpos:")?;

        // Unsigned division: r0 = |dividend|, r1 = |divisor|
        // Result: r2 = quotient, r0 = remainder
        writeln!(self.out, "    mov     r2, z")?; // quotient = 0
        writeln!(self.out, ".Ldm_loop:")?;
        writeln!(self.out, "    cls     r0, r1")?; // C = (dividend < divisor)
        writeln!(self.out, "    brt     .Ldm_done")?; // done if dividend < divisor
        writeln!(self.out, "    sub     r0, r1")?; // dividend -= divisor
        writeln!(self.out, "    add     r2, 1")?; // quotient++
        writeln!(self.out, "    bra     .Ldm_loop")?;
        writeln!(self.out, ".Ldm_done:")?;

        // r2 = |quotient|, r0 = |remainder|
        // Fix signs based on original operands
        writeln!(self.out, "    mov     r1, r0")?; // r1 = |remainder|
        writeln!(self.out, "    mov     r0, r2")?; // r0 = |quotient|

        // Pop original divisor and dividend to check signs
        writeln!(self.out, "    pop     r2")?; // r2 = original divisor
        writeln!(self.out, "    push    r0")?; // save |quotient|
        writeln!(self.out, "    push    r1")?; // save |remainder|

        // Negate remainder if original dividend was negative
        // sp-relative lw/sw not supported; use mov+lw via r0
        writeln!(self.out, "    mov     r0, sp")?;
        writeln!(self.out, "    lw      r0, 6(r0)")?; // original dividend (pushed first, 2 above)
        writeln!(self.out, "    cls     r0, z")?;
        writeln!(self.out, "    brf     .Ldm_rpos")?;
        writeln!(self.out, "    mov     r1, sp")?;
        writeln!(self.out, "    lw      r1, 0(r1)")?; // |remainder|
        writeln!(self.out, "    mov     r0, z")?;
        writeln!(self.out, "    sub     r0, r1")?;
        writeln!(self.out, "    mov     r1, sp")?;
        writeln!(self.out, "    sw      r0, 0(r1)")?; // remainder = -|remainder|
        writeln!(self.out, ".Ldm_rpos:")?;

        // Negate quotient if signs differ (dividend XOR divisor is negative)
        writeln!(self.out, "    mov     r0, sp")?;
        writeln!(self.out, "    lw      r0, 6(r0)")?; // original dividend
        writeln!(self.out, "    xor     r0, r2")?; // XOR with original divisor
        writeln!(self.out, "    cls     r0, z")?; // C = (XOR < 0) = signs differ
        writeln!(self.out, "    brf     .Ldm_qpos")?;
        writeln!(self.out, "    mov     r1, sp")?;
        writeln!(self.out, "    lw      r1, 3(r1)")?; // |quotient|
        writeln!(self.out, "    mov     r0, z")?;
        writeln!(self.out, "    sub     r0, r1")?;
        writeln!(self.out, "    mov     r1, sp")?;
        writeln!(self.out, "    sw      r0, 3(r1)")?; // quotient = -|quotient|
        writeln!(self.out, ".Ldm_qpos:")?;

        // Load results: r0 = quotient, r1 = remainder
        writeln!(self.out, "    pop     r1")?; // remainder
        writeln!(self.out, "    pop     r0")?; // quotient
        writeln!(self.out, "    pop     r2")?; // discard original dividend

        // Return: pop return address and jump
        writeln!(self.out, "    pop     r2")?; // return address
        writeln!(self.out, "    jmp     (r2)")?;
        writeln!(self.out)?;

        Ok(())
    }
}

// ── Utility functions ──────────────────────────────────────────────

/// Compute the frame offset for a local variable slot.
/// Local slot N is at fp - (N+1)*3.
fn local_frame_offset(slot: u8) -> Result<i8, EmitError> {
    let offset = -((slot as i16 + 1) * WORD as i16);
    if offset < -128 {
        return Err(EmitError::LocalOffsetTooLarge { offset: slot });
    }
    Ok(offset as i8)
}

/// Compute the frame offset for an argument.
/// `arg[idx]` is at `fp + FRAME_HEADER + (nargs - 1 - idx) * 3`.
fn arg_frame_offset(nargs: u8, idx: u8) -> i16 {
    FRAME_HEADER as i16 + (nargs as i16 - 1 - idx as i16) * WORD as i16
}

/// Sign-extend a 24-bit value stored in a u32 to an i32.
fn sign_extend_24(val: u32) -> i32 {
    if val & 0x80_0000 != 0 {
        (val | 0xFF00_0000) as i32
    } else {
        val as i32
    }
}

/// Pre-scan instructions to find all PCs that are branch/jump targets.
fn collect_branch_targets(instructions: &[Instruction]) -> HashSet<u32> {
    let mut targets = HashSet::new();
    for instr in instructions {
        match instr.op {
            Opcode::Jmp | Opcode::Jz | Opcode::Jnz | Opcode::Call | Opcode::Calln => {
                match instr.operand {
                    Operand::Imm24(addr) => {
                        targets.insert(addr);
                    }
                    Operand::D8A24 { addr, .. } => {
                        targets.insert(addr);
                    }
                    _ => {}
                }
            }
            _ => {}
        }
    }
    // Also mark procedure entry points
    for instr in instructions {
        if instr.op == Opcode::Enter {
            targets.insert(instr.pc);
        }
    }
    targets
}

#[cfg(test)]
mod tests {
    use super::*;
    use pcode_model::decode_program;

    /// Build a minimal p24 binary from instructions.
    fn make_p24(instructions: &[u8], global_count: u32) -> Vec<u8> {
        let code_size = instructions.len();
        let mut bin = Vec::new();
        // Header (18 bytes)
        bin.extend_from_slice(&[0x50, 0x32, 0x34, 0x00]); // magic
        bin.push(1); // version
                     // entry point: 0
        bin.push(0);
        bin.push(0);
        bin.push(0);
        // code size (LE24)
        bin.push((code_size & 0xFF) as u8);
        bin.push(((code_size >> 8) & 0xFF) as u8);
        bin.push(((code_size >> 16) & 0xFF) as u8);
        // data size: 0
        bin.push(0);
        bin.push(0);
        bin.push(0);
        // global count (LE24)
        bin.push((global_count & 0xFF) as u8);
        bin.push(((global_count >> 8) & 0xFF) as u8);
        bin.push(((global_count >> 16) & 0xFF) as u8);
        // flags
        bin.push(0);
        // Code segment
        bin.extend_from_slice(instructions);
        bin
    }

    #[test]
    fn emit_push_constant() {
        // push 42, halt
        let code: &[u8] = &[
            0x01, 0x2A, 0x00, 0x00, // push 42
            0x00, // halt
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("lc      r0, 42"));
        assert!(asm.contains("push    r0"));
        assert!(asm.contains("_p24_halt"));
    }

    #[test]
    fn emit_push_large_constant() {
        // push 1000 (0x0003E8)
        let code: &[u8] = &[
            0x01, 0xE8, 0x03, 0x00, // push 1000
            0x00, // halt
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("la      r0, 1000"));
    }

    #[test]
    fn emit_push_negative() {
        // push -1 (0xFFFFFF in 24-bit)
        let code: &[u8] = &[
            0x01, 0xFF, 0xFF, 0xFF, // push -1
            0x00,
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("lc      r0, -1"));
    }

    #[test]
    fn emit_add() {
        // push 3, push 4, add, halt
        let code: &[u8] = &[
            0x01, 0x03, 0x00, 0x00, // push 3
            0x01, 0x04, 0x00, 0x00, // push 4
            0x10, // add
            0x00, // halt
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("add     r0, r1"));
    }

    #[test]
    fn emit_sub() {
        let code: &[u8] = &[
            0x01, 0x0A, 0x00, 0x00, // push 10
            0x01, 0x03, 0x00, 0x00, // push 3
            0x11, // sub (10 - 3 = 7)
            0x00,
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("sub     r1, r0")); // r1=NOS, r0=TOS, r1=NOS-TOS
    }

    #[test]
    fn emit_comparison_eq() {
        let code: &[u8] = &[
            0x01, 0x05, 0x00, 0x00, // push 5
            0x01, 0x05, 0x00, 0x00, // push 5
            0x20, // eq
            0x00,
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("ceq     r0, r1"));
        assert!(asm.contains("mov     r0, c"));
    }

    #[test]
    fn emit_global_load_store() {
        // push 42, storeg 0, loadg 0, halt
        let code: &[u8] = &[
            0x01, 0x2A, 0x00, 0x00, // push 42
            0x45, 0x00, 0x00, 0x00, // storeg 0
            0x44, 0x00, 0x00, 0x00, // loadg 0
            0x00, // halt
        ];
        let bin = make_p24(code, 1);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("_p24_globals"));
        assert!(asm.contains("sw      r0, 0(r1)"));
        assert!(asm.contains("lw      r0, 0(r1)"));
    }

    #[test]
    fn emit_enter_with_locals() {
        // enter 2, push 10, storel 0, loadl 0, halt
        let code: &[u8] = &[
            0x40, 0x02, // enter 2
            0x01, 0x0A, 0x00, 0x00, // push 10
            0x43, 0x00, // storel 0
            0x42, 0x00, // loadl 0
            0x00, // halt
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("push    r1")); // save return address
        assert!(asm.contains("push    fp"));
        assert!(asm.contains("mov     fp, sp"));
        assert!(asm.contains("sub     sp, 6")); // 2 locals * 3 bytes
        assert!(asm.contains("-3(fp)")); // local 0 at fp-3
    }

    #[test]
    fn emit_conditional_jump() {
        // push 0, jz target, push 1, halt, target: push 2, halt
        let code: &[u8] = &[
            0x01, 0x00, 0x00, 0x00, // 0000: push 0
            0x31, 0x0D, 0x00, 0x00, // 0004: jz 0x000D
            0x01, 0x01, 0x00, 0x00, // 0008: push 1
            0x00, // 000C: halt
            0x01, 0x02, 0x00, 0x00, // 000D: push 2
            0x00, // 0011: halt
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("ceq     r0, z"));
        assert!(asm.contains("brf     .Lskip0"));
        assert!(asm.contains(".L000D:"));
    }

    #[test]
    fn emit_unconditional_jump() {
        // jmp 0x0004, halt, push 1, halt
        let code: &[u8] = &[
            0x30, 0x08, 0x00, 0x00, // 0000: jmp 0x0008
            0x01, 0x01, 0x00, 0x00, // 0004: push 1 (skipped)
            0x00, // 0008: halt
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("la      r2, .L0008"));
        assert!(asm.contains("jmp     (r2)"));
        assert!(asm.contains(".L0008:"));
    }

    #[test]
    fn emit_neg() {
        let code: &[u8] = &[
            0x01, 0x0A, 0x00, 0x00, // push 10
            0x15, // neg
            0x00,
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("mov     r0, z")); // r0 = 0
        assert!(asm.contains("sub     r0, r1")); // r0 = 0 - TOS
    }

    #[test]
    fn sign_extend_positive() {
        assert_eq!(sign_extend_24(0x00_0001), 1);
        assert_eq!(sign_extend_24(0x7F_FFFF), 8388607);
    }

    #[test]
    fn sign_extend_negative() {
        assert_eq!(sign_extend_24(0xFF_FFFF), -1);
        assert_eq!(sign_extend_24(0x80_0000), -8388608);
    }

    #[test]
    fn emit_call_and_ret() {
        // Main: push 42, call 0x0009, halt
        // Proc at 0x0009: enter 0, loada 0, drop, ret 1, leave
        let code: &[u8] = &[
            0x01, 0x2A, 0x00, 0x00, // 0000: push 42 (argument)
            0x33, 0x09, 0x00, 0x00, // 0004: call 0x0009
            0x00, // 0008: halt
            0x40, 0x00, // 0009: enter 0
            0x48, 0x00, // 000B: loada 0
            0x04, // 000D: drop
            0x34, 0x01, // 000E: ret 1
            0x41, // 0010: leave
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();

        // Call should use jal
        assert!(asm.contains("jal     r1, (r2)"));
        // Enter should save r1
        assert!(asm.contains("push    r1"));
        // Loada should access arg at fp+6 (nargs=1, idx=0: offset=6)
        assert!(asm.contains("lw      r0, 6(fp)"));
        // Ret should restore frame
        assert!(asm.contains("pop     fp"));
        assert!(asm.contains("jmp     (r2)"));
        // Ret should clean 1 arg (3 bytes)
        assert!(asm.contains("add     sp, 3"));
    }

    #[test]
    fn emit_sys_putc() {
        // push 65, sys 1, halt  (print 'A')
        let code: &[u8] = &[
            0x01, 0x41, 0x00, 0x00, // push 65
            0x60, 0x01, // sys 1 (putc)
            0x00, // halt
        ];
        let bin = make_p24(code, 0);
        let prog = decode_program(&bin).unwrap();
        let asm = emit_program(&prog, "test").unwrap();
        assert!(asm.contains("0xFF0100")); // UART address
        assert!(asm.contains("sb      r0, 0(r1)")); // write char
    }

    #[test]
    fn emit_full_program_from_p24_file() {
        let bin = std::fs::read(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../tests/p24/arithmetic.p24"
        ));
        if let Ok(bin) = bin {
            let prog = decode_program(&bin).unwrap();
            let asm = emit_program(&prog, "arithmetic.p24").unwrap();
            // Should have prologue, instructions, epilogue
            assert!(asm.contains("Generated by pc-aotc"));
            assert!(asm.contains("mov     sp, r0")); // sp init
            assert!(asm.contains("_p24_halt:"));
            // Should contain some of our supported opcodes
            assert!(asm.contains("push    r1")); // from enter (saves return addr)
            assert!(asm.contains("push    fp")); // from enter
            assert!(asm.contains("_p24_globals")); // globals section
        }
    }

    #[test]
    fn emit_procedure_call_program() {
        let bin = std::fs::read(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../tests/p24/procedure_call.p24"
        ));
        if let Ok(bin) = bin {
            let prog = decode_program(&bin).unwrap();
            let asm = emit_program(&prog, "procedure_call.p24").unwrap();
            // Should not contain any unsupported opcode TODOs for call/ret/sys/loada
            assert!(
                !asm.contains("TODO: unsupported opcode call"),
                "call should be supported"
            );
            assert!(
                !asm.contains("TODO: unsupported opcode ret"),
                "ret should be supported"
            );
            assert!(
                !asm.contains("TODO: unsupported opcode sys"),
                "sys should be supported"
            );
            assert!(
                !asm.contains("TODO: unsupported opcode loada"),
                "loada should be supported"
            );
            // Should contain jal for calls
            assert!(asm.contains("jal     r1, (r2)"));
            // Should contain UART access for putc
            assert!(asm.contains("0xFF0100"));
            // Should have divmod helper (write_int uses div/mod)
            assert!(asm.contains("_p24_divmod:"));
        }
    }

    #[test]
    fn arg_offset_calculation() {
        // nargs=1, idx=0: offset = 6 + (1-1-0)*3 = 6
        assert_eq!(arg_frame_offset(1, 0), 6);
        // nargs=2, idx=0: offset = 6 + (2-1-0)*3 = 9
        assert_eq!(arg_frame_offset(2, 0), 9);
        // nargs=2, idx=1: offset = 6 + (2-1-1)*3 = 6
        assert_eq!(arg_frame_offset(2, 1), 6);
        // nargs=3, idx=0: offset = 6 + (3-1-0)*3 = 12
        assert_eq!(arg_frame_offset(3, 0), 12);
    }
}
